# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e7b14068e1ccab9705fedd1e393c0adbd224b127198c59c26087dc84f90a876795b2cb78612e2320e4ee9186b197b592bb5e32ac226276487bd16e240daa06f

test:
  secret_key_base: bc945c15a76962f40d44b1537b8e6a707f33c019f9c02c61f3638c082e2b61d162e8e2805fabd8f4779cb93bc48dfd770f60b4971cc6b45a755a5bc1aa8e560a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
